import FWCore.ParameterSet.Config as cms

hltTiclTracksterLinks = cms.EDProducer("TracksterLinksProducer",
    arbitrationMaxSharedEnergyFraction = cms.double(0.2),
    cutTk = cms.string('1.48 < abs(eta) < 3.0 && pt > 1. && quality("highPurity") && hitPattern().numberOfLostHits("MISSING_OUTER_HITS") < 5'),
    detector = cms.string('HGCAL'),
    egammaInterpretationDescPSet = cms.PSet(
        algo_verbosity = cms.int32(0),
        delta_tk_sc = cms.double(0.1),
        eop_max = cms.double(1.5),
        eop_min = cms.double(0.5),
        min_em_fraction = cms.double(0.8),
        min_supercluster_energy = cms.double(1),
        type = cms.string('EGamma')
    ),
    egamma_tracksters_collections = cms.VInputTag("ticlTracksterLinksSuperclusteringDNN"),
    inferenceAlgo = cms.string(''),
    interpretationDescPSet = cms.PSet(
        algo_verbosity = cms.int32(0),
        delta_tk_ts_interface = cms.double(0.03),
        delta_tk_ts_layer1 = cms.double(0.02),
        energy_overshoot_fraction = cms.double(0.2),
        energy_overshoot_max = cms.double(10),
        timing_quality_threshold = cms.double(0.5),
        type = cms.string('ChargedHadron')
    ),
    jetInterpretationDescPSet = cms.PSet(
        algo_verbosity = cms.int32(0),
        delta_tk_ts = cms.double(0.1),
        min_trackster_energy = cms.double(5),
        recovery_max_eop = cms.double(3),
        recovery_min_eop = cms.double(0.2),
        type = cms.string('Jet')
    ),
    layer_clusters = cms.InputTag("hltMergeLayerClusters"),
    layer_clustersTime = cms.InputTag("hltMergeLayerClusters","timeLayerCluster"),
    linkingPSet = cms.PSet(
        algo_verbosity = cms.int32(0),
        cylinder_radius_sqr = cms.vdouble(9, 15),
        cylinder_radius_sqr_split = cms.double(9),
        deltaRxy = cms.double(4),
        dot_prod_th = cms.double(0.97),
        lower_boundary = cms.vdouble(20, 10),
        lower_distance_projective_sqr = cms.vdouble(4, 60),
        lower_distance_projective_sqr_closest_points = cms.vdouble(10, 50),
        max_z_distance_closest_points = cms.vdouble(35, 35),
        min_distance_z = cms.vdouble(35, 35),
        min_num_lcs = cms.uint32(15),
        min_trackster_energy = cms.double(20),
        onnxModelPath = cms.string(''),
        pca_quality_th = cms.double(0.85),
        proj_distance_split = cms.double(5),
        track_time_quality_threshold = cms.double(0.5),
        type = cms.string('Skeletons'),
        upper_boundary = cms.vdouble(150, 100),
        upper_distance_projective_sqr = cms.vdouble(4, 60),
        upper_distance_projective_sqr_closest_points = cms.vdouble(5, 30)
    ),
    mightGet = cms.optional.untracked.vstring,
    muonInterpretationDescPSet = cms.PSet(
        algo_verbosity = cms.int32(0),
        delta_tk_ts = cms.double(0.1),
        mip_energy_max = cms.double(10),
        onnx_model_path = cms.string(''),
        type = cms.string('Muon')
    ),
    muons = cms.InputTag("muons1stStep"),
    original_masks = cms.VInputTag("hltMergeLayerClusters:InitialLayerClustersMask"),
    pluginInferenceAlgoTracksterInferenceByDNN = cms.PSet(
        algo_verbosity = cms.int32(0),
        doPID = cms.int32(1),
        doRegression = cms.int32(1),
        eid_min_cluster_energy = cms.double(1),
        eid_n_clusters = cms.int32(10),
        eid_n_layers = cms.int32(50),
        inputNames = cms.vstring('input'),
        onnxEnergyModelPath = cms.string(''),
        onnxPIDModelPath = cms.string(''),
        output_en = cms.vstring('enreg_output'),
        output_id = cms.vstring('pid_output'),
        type = cms.string('TracksterInferenceByDNN')
    ),
    pluginInferenceAlgoTracksterInferenceByPFN = cms.PSet(
        algo_verbosity = cms.int32(0),
        doPID = cms.int32(1),
        doRegression = cms.int32(1),
        eid_min_cluster_energy = cms.double(1),
        eid_n_clusters = cms.int32(10),
        eid_n_layers = cms.int32(50),
        inputNames = cms.vstring(
            'input',
            'input_tr_features'
        ),
        miniBatchSize = cms.untracked.int32(64),
        onnxEnergyModelPath = cms.string(''),
        onnxPIDModelPath = cms.string(''),
        output_en = cms.vstring('enreg_output'),
        output_id = cms.vstring('pid_output'),
        type = cms.string('TracksterInferenceByPFN')
    ),
    propagator = cms.string('PropagatorWithMaterial'),
    regressionAndPid = cms.bool(False),
    runInterpretation = cms.bool(False),
    timingSoA = cms.InputTag("mtdSoA"),
    tracks = cms.InputTag("generalTracks"),
    tracksters_collections = cms.VInputTag("hltTiclTrackstersCLUE3DHigh", "hltTiclTrackstersRecovery"),
    useArbitration = cms.bool(False),
    useMTDTiming = cms.bool(True)
)
